name: Docker Image Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: ['7.4-apache-alpine', '8.0-apache-alpine']
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout recursively
        uses: actions/checkout@v2
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: "${{secrets.DOCKER_HUB_USERNAME}}"
          password: "${{secrets.DOCKER_HUB_ACCESS_TOKEN}}"
          logout: true

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{matrix.version}}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: managah/php:${{matrix.version}}
